<?php

function bs_misc_preprocess_page(&$vars) {

  drupal_add_js(drupal_get_path('module', 'bs_misc') . '/cookie-banner/src/cookie_config.js', array(
    'scope' => 'footer',
  ));
  drupal_add_js(drupal_get_path('module', 'bs_misc') . '/cookie-banner/dist/assets/js/cookie_banner.js', array(
    'scope' => 'footer',
  ));
  drupal_add_css(drupal_get_path('module', 'bs_misc').'/cookie-banner/dist/assets/css/styles.css');
}